kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-oc-mirror
subjects:
  - kind: ServiceAccount
    name: oc-mirror-sa
    namespace: oc-mirror
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
