apiVersion: v1
kind: ConfigMap
metadata:
  name: image-set-configuration
  namespace: oc-mirror
data:
  imagesetconfiguration.yaml: |
    apiVersion: mirror.openshift.io/v2alpha1
    kind: ImageSetConfiguration
    mirror:
      platform:
        architectures:
          - "amd64"
        graph: false
        channels:
          - name: stable-4.17
            type: ocp
            minVersion: 4.17.25
            maxVersion: 4.17.25
          - name: stable-4.18
            type: ocp
            minVersion: 4.18.9
            maxVersion: 4.18.9
      operators:
        - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17
          packages:
            - name: kubevirt-hyperconverged
              minVersion: 4.17.7
              maxVersion: 4.17.7
            - name: local-storage-operator
              minVersion: 4.17.0-202504092035
              maxVersion: 4.17.0-202504092035
            - name: kubernetes-nmstate-operator
              minVersion: 4.17.0-202504141105
              maxVersion: 4.17.0-202504141105
        - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
          packages:
            - name: kubevirt-hyperconverged
              minVersion: 4.18.2
              maxVersion: 4.18.2
            - name: local-storage-operator
              minVersion: 4.18.0-202504151633
              maxVersion: 4.18.0-202504151633
            - name: kubernetes-nmstate-operator
              minVersion: 4.18.0-202504160308
              maxVersion: 4.18.0-202504160308