apiVersion: v1
kind: ConfigMap
metadata:
  name: image-set-configuration
  namespace: oc-mirror
data:
  imagesetconfiguration.yaml: |
    apiVersion: mirror.openshift.io/v2alpha1
    kind: ImageSetConfiguration
    mirror:
      platform:
        architectures:
          - "amd64"
        graph: false
        channels:
          - name: stable-4.17
            type: ocp
            minVersion: 4.17.28
            maxVersion: 4.17.28
          - name: stable-4.18
            type: ocp
            minVersion: 4.18.12
            maxVersion: 4.18.12
      operators:
        - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17
          packages:
            - name: kubevirt-hyperconverged
              minVersion: 4.16.3
              maxVersion: 4.17.11
            - name: local-storage-operator
              minVersion: 4.17.0-202504281009
              maxVersion: 4.17.0-202504281009
            - name: kubernetes-nmstate-operator
              minVersion: 4.17.0-202505060707
              maxVersion: 4.17.0-202505060707
        - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
          packages:
            - name: kubevirt-hyperconverged
              minVersion: 4.17.4
              maxVersion: 4.18.3
            - name: local-storage-operator
              minVersion: 4.18.0-202505062100
              maxVersion: 4.18.0-202505062100
            - name: kubernetes-nmstate-operator
              minVersion: 4.18.0-202505061007
              maxVersion: 4.18.0-202505061007