apiVersion: v1
kind: ConfigMap
metadata:
  name: image-set-configuration
  namespace: oc-mirror
data:
  imagesetconfiguration.yaml: |
    apiVersion: mirror.openshift.io/v2alpha1
    kind: ImageSetConfiguration
    mirror:
      platform:
        architectures:
          - "amd64"
        graph: false
        channels:
          - name: stable-4.18
            type: ocp
            minVersion: 4.18.9
            maxVersion: 4.18.9
      operators:
          - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
            packages:
              - name: kubevirt-hyperconverged
              - name: local-storage-operator
              - name: nmstate-operator
