apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc-mirror-scratch
  namespace: oc-mirror
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
